### ISSUE TITLE
Undefined properties within log's data are not shown in log

### ISSUE THREAD

**Issue by keltika** [radixxko/liqd-logger#1]
https://github.com/radixxko/liqd-logger/blob/aac97e2583d82355e1bb096481026ee6ff343465/lib/log.js#L11

SERIALIZER( { a: 1, b: 'string', c: undefined } )
> '\n{\n  "a": 1,\n  "b": "string"\n}'

Suggested fix:
JSON.stringify( { a: 1, b: 'string', c: undefined }, (k,v) => v === undefined ? 'undefined' : v )
> '{"a":1,"b":"string","c":"undefined"}'

**Comment by m4x1m1l14n** [comment]
I would prefer option to define custom serializer to serialize log into XML for example.

**Comment by radixxko** [comment]
Fixed in `liqd-logger@0.0.4`

User can now define own format and serializer in the Logger constructor

`const logger = new Logger({ serializer: ( value ) => typeof value === 'object' ? JSON.stringify( value, (k,v) => v === undefined ? 'undefined' : v, '  ' ).replace(/^\{/,'\n{') : value });`
